# Generated by Django 2.2.5 on 2020-03-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='check_in',
        ),
    ]
